### ISSUE TITLE
Broken text

### ISSUE THREAD

**Issue by DiandraT** [SridharShrinidhi/confectionery-website-prototype#1]
Try using the white-space property for the paragraphs under "Our Story" for the smallest screen size, so the texts (Our store opening at France, and Christmas special , Ho ho ho!) don't awkwardly break.

**Comment by SridharShrinidhi** [comment]
@DiandraT I meant it to be that way, the text is supposed to be on two different lines, one the blog's title and the next line is a preview of the blogpost. I will change that line to ```a few lines from the post```.
